# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: 3.3.0
sudo: false
cache: packages
after_failure:
    - cat /home/travis/build/kittypr/RMDupdaterAddin/RMDupdaterAddin.Rcheck/00install.out
